config/routes.rb
Rails.application.routes.draw do

  
  
#for front-end routes
  root to: 'posts#index'
  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create] 


#this is CKeditor upload image sytax 
  mount Ckeditor::Engine => '/ckeditor'
#these are admin routes
  get '/login', to: 'admin/sessions#new'
  get '/logout', to: 'admin/sessions#destroy'
  namespace :admin do 
  	resources :traivans, only: [:index, :edit , :update]
  	resources :sessions, only: [:new, :create, :destroy]
    resources :posts
    resources :tags, except: [:index]
    resources :comments, only: [:index ,:update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :dashboards, only: [:index]
    resources :settings, only: [:new, :create, :edit, :update]
  end 
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notofications, as: :notifiable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor

  def mark_status
  	if status == false
  		update(status: true)
  	end
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :traivan

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags,  dependent: :destroy
  has_many :comments , dependent: :destroy

  validates :title , presence: true
  validates :content , presence: true
  

  def self.post_search(search)
  	where("title LIKE ? OR content LIKE ?", "%#{search}%" , "%#{search}%")
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :post_tags , dependent: :destroy
	has_many :posts, through: :post_tags , dependent: :destroy

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)
	end
end

app/models/traivan.rb
class Traivan < ApplicationRecord
	has_secure_password
	has_many :posts
	validates :fullname , presence: true 
	validates :username , format: {with: /@/ , message: 'Is not valid user'}
	validates :password , presence: true 
end

app/models/visitor.rb
class Visitor < ApplicationRecord
	has_many :notifications, as: :notifiable,dependent: :destroy
	has_many :comments ,dependent: :destroy
	has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time_ago time
		"#{time_ago_in_words(time)} ago"
	end

	def status_convert(status, truthy: nil, falsey: nil)
		if status
			truthy
		else
			falsey
		end
				
	end

	def admin_active? path
    "admin-active" if current_page? path
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/shared/_admin_head.html.erb
<div id="top-nav" class="container-fluid">
  <div class="row">
    <div class="col-lg-2 border-right ">
      <div class="admi-logo">
        <h5><%= Setting.first.site_name%></h5>
      </div>
    </div>
    <div class="col-lg-10 top-nav-link">
      <div class="top-link-inner">
        <!--nav icons-->
      <nav class="navbar navbar-expand-md">
        <div class="collapse navbar-collapse justify-content-end" id="myNavbar">
          <!--nav icons-->
          <ul class="navbar-nav icons">
          
            <li class="nav-item mr-4 icon">
              <%= link_to admin_comments_path , class: "nav-link" do %>
                <i class="far fa-bell"></i>
                <span class="label label-warning"><%= Comment.where(status: false).count%></span>
              <% end %>
            </li>
            <li class="nav-item mr-4 icon">
              <%= link_to admin_messages_path , class: "nav-link" do %>
                <i class="far fa-envelope"></i>
                <span class="label label-message"><%= Message.where(status: false).count%></span>
              <% end %>
            </li>
            <li class="nav-item mr-2 text-muted">
              <%= image_tag('https://s3.us-east-2.amazonaws.com/traivan-portfolio-bucket/0W8A4912.jpg' ,
                    width: "35",
                    class: "img-fluid rounded-circle")%> <%= Traivan.first.fullname%>
            </li>
            
          </ul>
        </div>
      </nav>
      </div>
    </div><!--end of col-lg-10-->
  </div>
</div>


  
 

app/views/shared/_admin_sidebar.html.erb
<nav class="col-md-3 col-lg-2 d-none d-md-block sidebar right-padding max-viewport" id="sidebar">
  <ul class="navbar-nav d-flex-column">
    <li class="nav-item mt-3 <%= admin_active? admin_dashboards_path%> ">
      <%= link_to admin_dashboards_path , class: "nav-link text-secondary" do %>
        <i class="fa fa-home  mr-2"></i> Dashboards
      <% end %>
    </li>

    <li class="nav-item py-1 <%= admin_active? admin_posts_path%> ">
      <%= link_to admin_posts_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-newspaper mr-2"></i> Article
      <% end %>
    </li>

    <li class="nav-item py-1 <%= admin_active? admin_messages_path%>">
      <%= link_to admin_messages_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-comment-alt mr-2"></i> Messages
      <% end %>
    </li>
    <li class="nav-item py-1 <%= admin_active? admin_comments_path%> ">
      <%= link_to admin_comments_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-comment-dots mr-2"></i> Comments
      <% end %>
    </li>
    <li class="nav-item py-1 <%= admin_active? new_admin_tag_path%> ">
      <%= link_to new_admin_tag_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-tag mr-2"></i> Tags
      <% end %>
    </li>
    <li class="nav-item py-1 <%= admin_active? admin_notifications_path%> ">
      <%= link_to admin_notifications_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-bell mr-2"></i> Notifications
      <% end %>
    </li>

    <li class="nav-item py-1 <%= admin_active? admin_traivans_path%> ">
      <%= link_to admin_traivans_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-user mr-2"></i> Administrator
      <% end %>
    </li>

    <li class="nav-item py-1">
      <%= link_to logout_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-sign-out-alt mr-2"></i> Sing out
      <% end %>
    </li>

    <li class="nav-item py-1 <%= admin_active? new_admin_setting_path%> ">
      <%= link_to new_admin_setting_path , class: "nav-link text-secondary" do %>
        <i class="fas fa-cog mr-2"></i> Settings
      <% end %>
    </li>
  </ul>
</nav>

app/views/shared/_alerts.html.erb
<%if flash[:notice]%>
	<div class="alert alert-success" role="alert">
		<%= flash[:notice]%>
	</div>
<% end %>

<%if flash[:alert]%>
	<div class="alert alert-danger" role="alert">
		<%= flash[:alert]%>
	</div>
<% end %>

app/views/shared/_font_awsome_link.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">