config/routes.rb
Rails.application.routes.draw do

  
  
#for front-end routes
  root to: 'posts#index'
  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create] 


#this is CKeditor upload image sytax 
  mount Ckeditor::Engine => '/ckeditor'
#these are admin routes
  get '/login', to: 'admin/sessions#new'
  get '/logout', to: 'admin/sessions#destroy'
  namespace :admin do 
  	resources :traivans, only: [:index, :edit , :update]
  	resources :sessions, only: [:new, :create, :destroy]
    resources :posts
    resources :tags, except: [:index]
    resources :comments, only: [:index ,:update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :dashboards, only: [:index]
    resources :settings, only: [:new, :create, :edit, :update]
  end 
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notofications, as: :notifiable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor

  def mark_status
  	if status == false
  		update(status: true)
  	end
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :traivan

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags,  dependent: :destroy
  has_many :comments , dependent: :destroy

  validates :title , presence: true
  validates :content , presence: true
  

  def self.post_search(search)
  	where("title LIKE ? OR content LIKE ?", "%#{search}%" , "%#{search}%")
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :post_tags , dependent: :destroy
	has_many :posts, through: :post_tags , dependent: :destroy

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)
	end
end

app/models/traivan.rb
class Traivan < ApplicationRecord
	has_secure_password
	has_many :posts
	validates :fullname , presence: true 
	validates :username , format: {with: /@/ , message: 'Is not valid user'}
	validates :password , presence: true 
end

app/models/visitor.rb
class Visitor < ApplicationRecord
	has_many :notifications, as: :notifiable,dependent: :destroy
	has_many :comments ,dependent: :destroy
	has_many :messages, dependent: :destroy
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  def new
    @tag = Tag.new
    @tags = Tag.order(id: :desc)
  end

  def create
    tags_params[:name].split(',').map do |n|
      Tag.new(name: n).save
    end
    redirect_to new_admin_tag_url, notice: "Tag was successful created"
  end

  def show
     @tag = Tag.find(params[:id])
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
     @tag = Tag.find(params[:id])
      if @tag.update(tags_params)
      redirect_to new_admin_tag_url, notice: "tag successful update"
    else
      flash[:alert] = "Tag was problem update"
      render :edit
    end
  end

  def destroy
     @tag = Tag.find(params[:id])
     @tag.destroy

     redirect_to new_admin_tag_url, notice: "Tag was successful delete"
  end

  private 
    def tags_params
      params.require(:tag).permit(:id, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time_ago time
		"#{time_ago_in_words(time)} ago"
	end

	def status_convert(status, truthy: nil, falsey: nil)
		if status
			truthy
		else
			falsey
		end
				
	end

	def admin_active? path
    "admin-active" if current_page? path
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/tags/edit.html.erb
<h1>Admin::Tags#edit</h1>
<%= form_for [:admin , @tag] do |f|%>
	<%= render 'validation_errors', object: @tag%>
	<div>
		<%= f.label :name%><br>
		<%= f.text_field :name %>
	</div>
	<div>
		<%= f.button :submit%>
	</div>
<% end %>

app/views/admin/tags/new.html.erb
<h1>Admin::Tags#new</h1>
<%= form_for [:admin, @tag] do |f|%>
	<div>
		<%= f.text_area :name, placeholder: "HTML ,RUBY ,CSS"%>
	</div>
	<div>
		<%= f.button :submit%>
	</div>
<% end %>

<hr>
<table>
	<thead>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>created</th>
			<th>status</th>
			<th>action</th>
		</tr>
	</thead>
	<tbody>
		<%@tags.each do |tag|%>
		<tr>
			<td><%= tag.id%></td>
			<td><%= tag.name%></td>
			<td><%= time_ago tag.created_at%></td>
			<td><%= status_convert(tag.in_use?, truthy: 'in use', falsey: 'not in use')  %></td>
			<td>
				<%= link_to  edit_admin_tag_path(tag) do %>
					<button type="button">Edit</button>
				<% end %>
				<%if tag.in_use?%>
					<%= link_to  '#' do %>
						<button type="button" class="disabled">Delete</button>
					<% end %>
				<% else %>
					<%= link_to  admin_tag_path(tag), method: :delete, data: {confirm: "are your sure?"} do %>
						<button type="button">Delete</button>
					<% end %>
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/tags/show.html.erb
<h1>Admin::Tags#show</h1>
<p>Find me in app/views/admin/tags/show.html.erb</p>