config/routes.rb
Rails.application.routes.draw do

  
  
#for front-end routes
  root to: 'posts#index'
  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create] 


#this is CKeditor upload image sytax 
  mount Ckeditor::Engine => '/ckeditor'
#these are admin routes
  get '/login', to: 'admin/sessions#new'
  get '/logout', to: 'admin/sessions#destroy'
  namespace :admin do 
  	resources :traivans, only: [:index, :edit , :update]
  	resources :sessions, only: [:new, :create, :destroy]
    resources :posts
    resources :tags, except: [:index]
    resources :comments, only: [:index ,:update, :destroy]
    resources :visitors, only: [:index, :destroy]
    resources :messages, only: [:index, :show, :update, :destroy]
    resources :notifications, only: [:index, :destroy]
    resources :dashboards, only: [:index]
    resources :settings, only: [:new, :create, :edit, :update]
  end 
  match 'dismiss_all_notifications', to: 'admin/notifications#delete_all', via: :delete
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :visitor
  has_many :notofications, as: :notifiable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor

  def mark_status
  	if status == false
  		update(status: true)
  	end
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :traivan

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags,  dependent: :destroy
  has_many :comments , dependent: :destroy

  validates :title , presence: true
  validates :content , presence: true
  

  def self.post_search(search)
  	where("title LIKE ? OR content LIKE ?", "%#{search}%" , "%#{search}%")
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :post_tags , dependent: :destroy
	has_many :posts, through: :post_tags , dependent: :destroy

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)
	end
end

app/models/traivan.rb
class Traivan < ApplicationRecord
	has_secure_password
	has_many :posts
	validates :fullname , presence: true 
	validates :username , format: {with: /@/ , message: 'Is not valid user'}
	validates :password , presence: true 
end

app/models/visitor.rb
class Visitor < ApplicationRecord
	has_many :notifications, as: :notifiable,dependent: :destroy
	has_many :comments ,dependent: :destroy
	has_many :messages, dependent: :destroy
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::ApplicationController
  def index
  	@posts = Post.last(5)
  	@comments = Comment.last(5)
  	@visitors = Visitor.last(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time_ago time
		"#{time_ago_in_words(time)} ago"
	end

	def status_convert(status, truthy: nil, falsey: nil)
		if status
			truthy
		else
			falsey
		end
				
	end

	def admin_active? path
    "admin-active" if current_page? path
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/dashboards/index.html.erb
<h1>Dashboard</h1>
<%= link_to 'new post' , new_admin_post_path%>
<%= link_to 'views all ' , admin_posts_path%>
<table>
	<thead>
		<tr>
			<th>id</th>
			<th>title</th>
			<th>replied</th>
			<th>created</th>
			<th>action</th>
		</tr>
	</thead>
	<tbody>
		<%@posts.each do |post|%>
		<tr>
			<td><%= post.id%></td>
			<td><%= truncate(post.title, length: 40, seperator: '')%></td>
			<td><%= post.comments.count%></td>
			
			<td><%= time_ago post.created_at%></td>
			<td>
				<%= link_to 'edit', edit_admin_post_path(post)%>
				<%= link_to 'view', admin_post_path(post)%>
				<%= link_to 'del', admin_post_path(post), method: :delete, data: {confirm: 'are you sure?'}%>
					
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
<hr>
<h2>Comments</h2>
<%@comments.each do |comment|%>
	<p><%= comment.visitor.fullname%></p>
	<p><%= truncate(comment.message, length: 125, seperator: '')%></p>
	<p><%= time_ago comment.created_at%></p>
<% end %>

<hr>
<table>
	<tbody>
		<tr>
			<th>#</th>
			<th>Full name</th>
			<th>Email</th>
			<th>Created</th>
			<th>Action</th>
		</tr>
	</tbody>
	<tbody>
		<%@visitors.each_with_index do |visitor, index|%>
		<tr>
			<td><%= index + 1%></td>
			<td><%= visitor.fullname%></td>
			<td><%= visitor.email%></td>
			<td><%= time_ago visitor.created_at%></td>
			<td><%= link_to 'delete', admin_visitor_path(visitor), method: :delete, data: {confirm: 'are you sure ?'}%></td>
		</tr>
		<% end %>
	</tbody>
</table>